apiVersion: v1
kind: Pod
metadata:
  name: check-pvc
spec:
  containers:
    - name: check-pv-container
      image: ubuntu
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: false
        runAsGroup: 70
        runAsNonRoot: true
        runAsUser: 70
      resources:
        limits:
          cpu: 50m
          memory: 30Gi
        requests:
          cpu: 50m
          memory: 30Gi
      volumeMounts:
        - name: wieger-01
          mountPath: "/app/data/"
  volumes:
    - name: wieger-01
      persistentVolumeClaim:
        claimName: wieger-01
  securityContext:
    seccompProfile:
      type: RuntimeDefault