apiVersion: v1
kind: Pod
metadata:
  name: test-nfs
spec:
  containers:
    - name: shell
      image: ubuntu
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: false
        runAsGroup: 70
        runAsNonRoot: true
        runAsUser: 70
      volumeMounts:
        - name: nfs-01
          mountPath: "/app/data"
      resources:
        limits:
          cpu: 50m
          memory: 30Gi
        requests:
          cpu: 50m
          memory: 30Gi
  volumes:
    - name: nfs-01
      persistentVolumeClaim:
        claimName: nfs-01
  securityContext:
    seccompProfile:
      type: RuntimeDefault
