apiVersion: v1
kind: Pod
metadata:
  name: experiment-job
spec:
    restartPolicy: Never  # Define restartPolicy here
    volumes:
     - name: nfs-01
       persistentVolumeClaim:
         claimName: nfs-01
    containers:
      - name: experiment
        image: wpunter/omnisketch2lhs:latest
        command:
          - /bin/sh
        args:
          - -c
          - while true; do echo hello; sleep 100;done
        #args: ["Test_two_LHS", "synthEquiDepthBins", "4"]  # Replace with your actual parameters
        resources:
          limits:
            cpu: 44
            memory: 500Gi
            power.intel.com/performance: 44
          requests:
            cpu: 44
            memory: 500Gi
            power.intel.com/performance: 44
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: false
          runAsGroup: 70
          runAsNonRoot: true
          runAsUser: 70
        volumeMounts:
          - name: nfs-01
            mountPath: "/app/data/"

    imagePullSecrets:
      - name: dockerhub-secret
    securityContext:
      seccompProfile:
        type: RuntimeDefault
